version: 2.1
orbs:
  architect: giantswarm/architect@4.37.0

jobs:
  unit-tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: CGO_ENABLED=0 make test-unit
  integration-tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run integration tests"
          command: CGO_ENABLED=0 make test-integration
  acceptance-tests:
    executor: architect/machine
    machine:
      image: 'ubuntu-2004:2023.04.2'
    steps:
      - checkout
      - architect/machine-install-go
      - architect/integration-test-install-tools:
          apptestctl-version: v0.14.5
          helm-version: v3.10.2
          kubernetes-version: v1.25.0
      - run:
          name: "Run acceptance tests"
          command: CGO_ENABLED=0 make test-acceptance

workflows:
  test-and-push:
    jobs:
      - unit-tests:
          filters:
            tags:
              only: /^v.*/
      - integration-tests:
          filters:
            tags:
              only: /^v.*/
      - acceptance-tests:
          filters:
            tags:
              only: /^v.*/
      - architect/go-build:
          context: architect
          name: go-build
          binary: aws-network-topology-operator
          resource_class: xlarge
          requires:
            - unit-tests
            - integration-tests
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "aws-network-topology-operator"
          requires:
            - push-to-registries
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "aws-network-topology-operator"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-to-app-catalog
            - push-to-registries
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
