name: aws-network-topology-operator
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/aws-network-topology-operator
  tag: v0.0.1
  pullPolicy: IfNotPresent
