project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/aws-network-topology-operator
  tag: "[[ .Version ]]"
  pullPolicy: IfNotPresent

managementCluster:
  name: ""
  namespace: ""
