project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/aws-network-topology-operator
  tag: "[[ .Version ]]"
  pullPolicy: IfNotPresent

managementCluster:
  name: ""
  namespace: ""

pod:
  user:
    id: "65532"
  group:
    id: "65532"

aws:
  accessKeyID: accesskey
  secretAccessKey: secretkey
  region: region

serviceType: "managed"
userManaged:
  # snsTopic defins the SNS topic to send TGW attatchment requests to when running in UserManaged mode.
  snsTopic: ""

# Add seccomp to pod security context
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  seccompProfile:
    type: RuntimeDefault
