apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
  {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
  {{- include "labels.selector" . | nindent 6 }}
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
    {{- include "labels.selector" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "resource.default.name"  . }}
      securityContext:
        runAsUser: {{ .Values.pod.user.id }}
        runAsGroup: {{ .Values.pod.group.id }}
        {{- with .Values.podSecurityContext }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command:
            - /manager
          args:
            - --leader-elect
            - --management-cluster-name={{ required "The name of the management cluster is required" .Values.managementCluster.name }}
            - --management-cluster-namespace={{ required "The namespace of the management cluster is required" .Values.managementCluster.namespace }}
            {{- if .Values.userManaged.snsTopic }}
            - --sns-topic={{.Values.userManaged.snsTopic }}
            {{- end }}
          env:
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: /home/.aws/credentials
          securityContext:
            {{- with .Values.securityContext }}
              {{- . | toYaml | nindent 12 }}
            {{- end }}
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 80Mi
          volumeMounts:
          - mountPath: /home/.aws
            name: credentials
      volumes:
      - name: credentials
        secret:
          secretName: {{ include "resource.default.name" . }}-aws-credentials
