apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" . }}-aws-credentials
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
stringData:
  credentials: |-
    [default]
    aws_access_key_id: {{ .Values.aws.accessKeyID | quote }}
    aws_secret_access_key: {{ .Values.aws.secretAccessKey | quote }}
    region: {{ .Values.aws.region | quote }}
